#!/usr/bin/python3

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'), 'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

monitor = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.NetworkMonitor')

try:
	servingcell = monitor.GetServingCellInformation()
except dbus.DBusException as e:
	print("Unable to get serving cell information")
	exit()

tech = 'Technology'
mcc = 'MobileCountryCode'
mnc = 'MobileNetworkCode'
lac = 'LocationAreaCode'
cid = 'CellId'
psc = 'PrimaryScramblingCode'
rssi = 'Strength'
ber = 'BitErrorRate'
rxlev = 'ReceivedSignalStrength'
rscp = 'ReceivedSignalCodePower'
ecn0 = 'ReceivedEnergyRatio'
rsrq = 'ReferenceSignalReceivedQuality'
rsrp = 'ReferenceSignalReceivedPower'
op = 'Operator'
earfcn = 'EARFCN'
lband = 'LBand'
ul_BW = 'UplinkResourceBlocks'
dl_BW = 'DownlinkResourceBlocks'
tac = 'TrackingAreaCode'
sinr = 'SignalNoiseRatio'
cqi = 'ChannelQuality'
avg_rsrp = 'AverageRSRP'

print("Current serving cell information:")

if tech in servingcell:
	print("    [ Radio Access Technology = %s]" % (servingcell[tech]))

if mcc in servingcell:
	print("    [ Mobile Country Code = %s]" % (servingcell[mcc]))

if mnc in servingcell:
	print("    [ Mobile Network Code = %s]" % (servingcell[mnc]))

if lac in servingcell:
	print("    [ Location Area Code = %d]" % (servingcell[lac]))

if cid in servingcell:
	print("    [ Cell Identity = %d]" % (servingcell[cid]))

if psc in servingcell:
	print("    [ Primary Scrambling Code = %d]" % (servingcell[psc]))

if rssi in servingcell:
	print("    [ Signal Strength = %d]" % (servingcell[rssi]))

if rxlev in servingcell:
	print("    [ Received Signal Strength = %d]" % (servingcell[rxlev]))

if ber in servingcell:
	print("    [ Bit Error Rate = %d]" % (servingcell[ber]))

if rscp in servingcell:
	print("    [ Received Signal Code Power = %f]" % (servingcell[rscp]))

if ecn0 in servingcell:
	print("    [ Received Energy Ratio = %d]" % (servingcell[ecn0]))

if rsrq in servingcell:
	print("    [ Reference Signal Received Quality = %f]" % (servingcell[rsrq]))

if rsrp in servingcell:
	print("    [ Reference Signal Received Power = %d]" % (servingcell[rsrp]))

if op in servingcell:
	print("    [ Operator = %s ]" % (servingcell[op]))

if earfcn in servingcell:
	print("    [ E-UTRAN Absolue Radio Frequency Channel = %d ]" % (servingcell[earfcn]))

if lband in servingcell:
	print("    [ LBand = %d ]" % (servingcell[Lband]))

if ul_BW in servingcell:
	print("    [ Uplink Resource Blocks = %d ]" % (servingcell[ul_BW]))

if dl_BW in servingcell:
	print("    [ Downlink Resource Blocks = %d ]" % (servingcell[dl_BW]))

if tac in servingcell:
	print("    [ Tracking Area Code = %d ]" % (servingcell[tac]))

if sinr in servingcell:
	print("    [ Signal to Interference and Noise Ratio = %d ]" % (servingcell[sinr]))

if cqi in servingcell:
	print("    [ Channel Quality Indicator = %d ]" % (servingcell[cqi]))

if avg_rsrp in servingcell:
	print("    [ Average last 10th Reference Signal Received Power = %d ]" % (servingcell[avg_rsrp]))


print('')
