#!/usr/bin/python3

import dbus, sys

bus = dbus.SystemBus()

if len(sys.argv) == 3:
	path = sys.argv[1]
	netmode = sys.argv[2]
elif len(sys.argv) == 2:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	netmode = sys.argv[1]
else:
	print("%s [PATH] network-mode" % (sys.argv[0]))
	print("")
	print(" network-mode must be either \"routed\" or \"bridged\"")

# suppport also mode strings like "bridge" or "router"
if netmode == "bridge":
	netmode = "bridged"

if netmode == "router":
	netmode = "routed"

print("Setting networking mode for modem %s to %s..." % (path, netmode))
modem = dbus.Interface(bus.get_object('org.ofono', path), 'org.ofono.Modem')

modem.SetProperty("NetworkMode", dbus.String(netmode));

